### ISSUE TITLE
Automatically escape special characters?

### ISSUE THREAD

**Issue by ResistanceIsUseless** [Aesthetikx/openai_pipe#3]
This is probably a terminal issue and not something related to openai_pipe, but I figured I would open an issue anyways. It's annoying to remember to use quotes or escape special characters.

```
➜  ~ ai what is the command to search for a file on linux?
zsh: no matches found: linux?
➜  ~ ai "what is the command to search for a file on linux?"
The command to search for a file on Linux is "find".
➜  ~ ai what is the command to search for a file on linux\?       
The command to search for a file on Linux is:

find / -name <filename>
```

**Comment by Aesthetikx** [comment]
What shell are you using, e.g. bash, zsh, dash, etc? (`echo $SHELL`)

Edit: Oh I see, zsh

**Comment by Aesthetikx** [comment]
It is possible that you have some other sort of configuration going on, for me that works with zsh.

```
~ % echo $SHELL && ai what is your name?
/usr/local/bin/zsh
My name is Hannah.
```
